# This is a basic workflow to help you get started with Actions

name: Deploy infrastructure

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
    paths:
      - 'module07/demo-infra/**'
      
jobs:
  terraform:
    runs-on: ubuntu-latest
    
    name: 'deploy infrastructure'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./module07/demo-infra
      
    steps:
      # Step 1: Check out the repository to the runner
      - uses: actions/checkout@v4

      # Step 2: Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6  # Specify the desired version of Terraform

      # Step 3: Initialize Terraform
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}
      
      # Step 4: Generate a plan for Terraform changes
      - name: Terraform plan
        id: plan
        run: terraform plan
        working-directory: ${{ env.WORKING_DIR }}
      
      # Step 5: Apply Terraform changes
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORKING_DIR }}
