name: Validate Infrastructure

on:
  # Triggers the workflow on push or pull request events
  push:
    branches-ignore:
      - "main"
    paths:
      - "module07/demo-infra/**"

jobs:
  terraform:
    name: "Validate"
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./module07/demo-infra

    steps:
      # Checkout the repository to the runner
      - uses: actions/checkout@v2

      # Install Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6 # Specify the desired Terraform version

      # Initialize Terraform
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      # Validate the Terraform configuration
      - name: Terraform validate
        id: validate
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}
